### ISSUE TITLE
centos7 ml804 ml does not start properly

### ISSUE THREAD

**Issue by hugokoopmans** [rlouapre/docker-ml#2]
Hi, I used the dockerfile to  build an image like so:
`docker build --rm=true -t "centos7-ml804" .`

And logged in to see what is happening like so:
`docker run -i -t centos7-ml804:latest /bin/bash`

When I try to start ML by hand I get:

```
root@e36cb4cb20fd /]# /etc/init.d/MarkLogic start
Starting MarkLogic: /opt/MarkLogic/bin/MarkLogic: error while loading shared libraries: libsasl2.so.2: cannot open shared object file: No such file or directory
                                                           [FAILED]
[root@e36cb4cb20fd /]# 
```

Any suggestions?

Preferably I would like to use docker-compose, so I can create multiple containers.

Also I would like to do the setup of ml once and then create a new image from that to be uploaded into my private regiistry, any tips there?

thx

**Comment by rlouapre** [comment]
There is no need to start ML. `supervisord` does it for you.

Why would you need to start manually?

**Comment by rlouapre** [comment]
And yes . you can build the image and store it in your private repository (that's actually how I use it).

**Comment by hugokoopmans** [comment]
ok theres two issues here:
1) If I run from centos 7 I get the above error, please advise on that.
2) If I run from centos 6  it seems supervisor is not starting marklogic automatically...
so after the build and start of a container I have to manually go into the container and start MarkLogic ...

**Comment by rlouapre** [comment]
1) That's expected. You need to use a different rpm package for centos7. From the README 

> For CentOS7 use REHL 7 rpm

2) For centos 6 use CentOS 6 rpm

**Comment by hugokoopmans** [comment]
Ha ok my bad ...
