### ISSUE TITLE
can i create a running ml instance, passing the self-install part?

### ISSUE THREAD

**Issue by hugokoopmans** [rlouapre/docker-ml#3]
Hi,

Would it be possible to pass the self-install part to be able to deploy a running ML instance without the need to go into the container and 'self-install' ml ...?

Can it be done or do I need to commit from a container?

hugo

**Comment by rlouapre** [comment]
You could use this script [1].

I have also planned to build a small cli using Docker API to discover the instances and setup a cluster but unfortunately this tool is not available yet.

[1] - https://docs.marklogic.com/guide/admin-api/cluster#id_39116

**Comment by hugokoopmans** [comment]
ok so I could add this bash script to the DockerFile and add default credetials to the admin user/passwd and then it should be possible to setup a ML image that is already up and running with that admin?

**Comment by rlouapre** [comment]
yes - that's what I usually do [1]

[1] - https://github.com/nativelogix/xquerrail2.framework/blob/master/circle.yml

**Comment by hugokoopmans** [comment]
wow that is _advanced_ stuff, you integrate roxy app deployment and docker ... cool ...
would be nice to add an example in between the basic readme and this last part. but i will dive in thx
hugo

**Comment by hugokoopmans** [comment]
just one more question , is circle.yml  a docker-compose file? 
or is that another type op build file?
thx

**Comment by rlouapre** [comment]
That's not a docker-compose file. It is circle CI configuration file [1].

[1] - https://circleci.com/docs/configuration
